export const TECH_STACK = [
  // ─────────── LANGUAGES ───────────
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Dart",
  "Scala",
  "Haskell",
  "Elixir",
  "R",
  "MATLAB",
  ".NET",

  // ─────────── FRONTEND FRAMEWORKS ───────────
  "React",
  "Next.js",
  "Angular",
  "Vue.js",
  "Svelte",
  "Solid.js",
  "Astro",
  "Gatsby",
  "Bootstrap",
  "Tailwind CSS",

  // ─────────── BACKEND FRAMEWORKS ───────────
  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "Go Fiber",
  "Phoenix Elixir",

  // ─────────── DATABASES ───────────
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQL Server",
  "SQLite",
  "Firebase",
  "Supabase",
  "Redis",
  "ElasticSearch",
  "MariaDB",

  // ─────────── AI / ML ───────────
  "TensorFlow",
  "PyTorch",
  "Scikit‑Learn",
  "Pandas",
  "NumPy",
  "LangChain",
  "Transformers",
  "OpenAI API",
  "HuggingFace",
  "Keras",

  // ─────────── DEVOPS ───────────
  "Docker",
  "Kubernetes",
  "Jenkins",
  "GitHub Actions",
  "Terraform",
  "AWS",
  "GCP",
  "Azure",
  "Vercel",
  "Netlify",

  // ─────────── MOBILE ───────────
  "Flutter",
  "React Native",
  "Android",
  "iOS",
  "SwiftUI",

  // ─────────── BLOCKCHAIN ───────────
  "Solidity",
  "Web3.js",
  "Ethers.js",
  "Hardhat",
  "Rust Solana",

  // ─────────── OTHER ───────────
  "GraphQL",
  "WebSockets",
  "Socket.io",
  "Stripe API",
  "REST API",
];
